PREFIX vh: <http://localhost:3030/vietheritage/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?site ?label WHERE {
  ?site a vh:UNESCOHeritageSite ; rdfs:label ?label .
}
ORDER BY ?site
