PREFIX vh: <http://localhost:3030/vietheritage/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?entity ?person ?label WHERE {
  ?entity vh:associatedWithPerson ?person ; rdfs:label ?label .
}
ORDER BY ?entity
