PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?class (COUNT(?entity) AS ?count) WHERE {
  ?entity a ?class .
  FILTER(?class != <http://www.w3.org/2002/07/owl#NamedIndividual>)
}
GROUP BY ?class
ORDER BY DESC(?count)
