PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?entity ?label ?lat ?lon WHERE {
  ?entity rdfs:label ?label ; geo:lat ?lat ; geo:long ?lon .
}
ORDER BY ?entity
