PREFIX vh: <http://localhost:3030/vietheritage/ontology/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?site ?viLabel ?externalResource ?enLabel
WHERE {
  ?site a vh:HeritageSite ; rdfs:label ?viLabel ; owl:sameAs ?externalResource .
  ?externalResource rdfs:label ?enLabel .
  FILTER(LANG(?viLabel) = "vi")
  FILTER(LANG(?enLabel) = "en")
  FILTER(?site != ?externalResource)
}
ORDER BY ?site
